CC = gcc
TARGET1 = NumberCross

run : $(TARGET1)
	  rm formula

$(TARGET1) :
	$(CC) NumberCross.c -o $(TARGET1)
	./$(TARGET1)
	rm $(TARGET1)

exe :
	$(CC) NumberCross.c -o $(TARGET1) 

clean:
	rm $(TARGET1)